version: '3.3'

volumes:
  pg_data_foodgram:
  static_foodgram:
  media_foodgram:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data/
    env_file: .env
  backend:
    image: nikitriy1/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_foodgram:/backend_static/
      - media_foodgram:/app/media/
  frontend:
    image: nikitriy1/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_foodgram:/frontend_static/
    env_file: .env
  nginx:
    image: nikitriy1/foodgram_nginx
    ports:
      - 9000:80
    volumes:
      - static_foodgram:/static/
      - media_foodgram:/app/media/
