# Generated by Django 4.2.4 on 2023-08-05 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"ordering": ["-pk"]},
        ),
    ]
