# Generated by Django 4.2.4 on 2023-08-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_options_alter_subscription_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="is_subscribed",
        ),
        migrations.AlterField(
            model_name="subscription",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
    ]
